# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'URgui.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 717)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(360, 10, 201, 221))
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 182, 182))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.base_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.base_joint_lEdit.setObjectName("base_joint_lEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.base_joint_lEdit)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.shoulder_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.shoulder_joint_lEdit.setObjectName("shoulder_joint_lEdit")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.shoulder_joint_lEdit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.elbow_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.elbow_joint_lEdit.setObjectName("elbow_joint_lEdit")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.elbow_joint_lEdit)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.wrist1_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.wrist1_joint_lEdit.setObjectName("wrist1_joint_lEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.wrist1_joint_lEdit)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.wrist2_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.wrist2_joint_lEdit.setObjectName("wrist2_joint_lEdit")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.wrist2_joint_lEdit)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.wrist3_joint_lEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.wrist3_joint_lEdit.setObjectName("wrist3_joint_lEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.wrist3_joint_lEdit)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 331, 391))
        self.groupBox_2.setObjectName("groupBox_2")
        self.info_textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        self.info_textEdit.setGeometry(QtCore.QRect(10, 30, 311, 351))
        self.info_textEdit.setObjectName("info_textEdit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 230, 231, 211))
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 30, 211, 174))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.input_joint_angle_lEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_joint_angle_lEdit.setObjectName("input_joint_angle_lEdit")
        self.verticalLayout.addWidget(self.input_joint_angle_lEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.move_joint_angle_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.move_joint_angle_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.move_joint_angle_btn.setObjectName("move_joint_angle_btn")
        self.horizontalLayout.addWidget(self.move_joint_angle_btn)
        self.clear_angle_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_angle_btn.setObjectName("clear_angle_btn")
        self.horizontalLayout.addWidget(self.clear_angle_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.input_joint_radian_lEdit = QtWidgets.QLineEdit(self.layoutWidget1)
        self.input_joint_radian_lEdit.setObjectName("input_joint_radian_lEdit")
        self.verticalLayout_2.addWidget(self.input_joint_radian_lEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.move_joint_radian_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.move_joint_radian_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.move_joint_radian_btn.setObjectName("move_joint_radian_btn")
        self.horizontalLayout_2.addWidget(self.move_joint_radian_btn)
        self.clear_radian_btn = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_radian_btn.setObjectName("clear_radian_btn")
        self.horizontalLayout_2.addWidget(self.clear_radian_btn)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(590, 230, 231, 321))
        self.groupBox_4.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.groupBox_4.setObjectName("groupBox_4")
        self.init2final_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.init2final_btn.setGeometry(QtCore.QRect(10, 250, 211, 25))
        self.init2final_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.init2final_btn.setObjectName("init2final_btn")
        self.final2init_btn = QtWidgets.QPushButton(self.groupBox_4)
        self.final2init_btn.setGeometry(QtCore.QRect(10, 290, 211, 25))
        self.final2init_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.final2init_btn.setObjectName("final2init_btn")
        self.show_init_pos_tedit = QtWidgets.QTextEdit(self.groupBox_4)
        self.show_init_pos_tedit.setGeometry(QtCore.QRect(10, 90, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.show_init_pos_tedit.setFont(font)
        self.show_init_pos_tedit.setObjectName("show_init_pos_tedit")
        self.show_final_pos_tedit = QtWidgets.QTextEdit(self.groupBox_4)
        self.show_final_pos_tedit.setGeometry(QtCore.QRect(10, 200, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.show_final_pos_tedit.setFont(font)
        self.show_final_pos_tedit.setObjectName("show_final_pos_tedit")
        self.label_10 = QtWidgets.QLabel(self.groupBox_4)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 162, 17))
        self.label_10.setObjectName("label_10")
        self.widget = QtWidgets.QWidget(self.groupBox_4)
        self.widget.setGeometry(QtCore.QRect(10, 160, 201, 27))
        self.widget.setObjectName("widget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.get_final_ur_pos_btn = QtWidgets.QPushButton(self.widget)
        self.get_final_ur_pos_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.get_final_ur_pos_btn.setObjectName("get_final_ur_pos_btn")
        self.horizontalLayout_4.addWidget(self.get_final_ur_pos_btn)
        self.clear_final_ledit_btn = QtWidgets.QPushButton(self.widget)
        self.clear_final_ledit_btn.setObjectName("clear_final_ledit_btn")
        self.horizontalLayout_4.addWidget(self.clear_final_ledit_btn)
        self.label_9 = QtWidgets.QLabel(self.groupBox_4)
        self.label_9.setGeometry(QtCore.QRect(11, 31, 149, 17))
        self.label_9.setObjectName("label_9")
        self.widget1 = QtWidgets.QWidget(self.groupBox_4)
        self.widget1.setGeometry(QtCore.QRect(11, 54, 211, 27))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.get_init_ur_pos_btn = QtWidgets.QPushButton(self.widget1)
        self.get_init_ur_pos_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.get_init_ur_pos_btn.setObjectName("get_init_ur_pos_btn")
        self.horizontalLayout_3.addWidget(self.get_init_ur_pos_btn)
        self.clear_init_ledit_btn = QtWidgets.QPushButton(self.widget1)
        self.clear_init_ledit_btn.setObjectName("clear_init_ledit_btn")
        self.horizontalLayout_3.addWidget(self.clear_init_ledit_btn)
        self.groupBox_5 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(580, 10, 241, 221))
        self.groupBox_5.setStyleSheet("border-color: rgb(46, 52, 54);")
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.x_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.x_ee_lEdit.setObjectName("x_ee_lEdit")
        self.horizontalLayout_9.addWidget(self.x_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.y_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.y_ee_lEdit.setObjectName("y_ee_lEdit")
        self.horizontalLayout_11.addWidget(self.y_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.z_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.z_ee_lEdit.setObjectName("z_ee_lEdit")
        self.horizontalLayout_12.addWidget(self.z_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_13.addWidget(self.label_14)
        self.th_x_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_x_ee_lEdit.setObjectName("th_x_ee_lEdit")
        self.horizontalLayout_13.addWidget(self.th_x_ee_lEdit)
        self.th_x_rad_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_x_rad_ee_lEdit.setObjectName("th_x_rad_ee_lEdit")
        self.horizontalLayout_13.addWidget(self.th_x_rad_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_14.addWidget(self.label_15)
        self.th_y_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_y_ee_lEdit.setObjectName("th_y_ee_lEdit")
        self.horizontalLayout_14.addWidget(self.th_y_ee_lEdit)
        self.th_y_rad_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_y_rad_ee_lEdit.setObjectName("th_y_rad_ee_lEdit")
        self.horizontalLayout_14.addWidget(self.th_y_rad_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.th_z_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_z_ee_lEdit.setObjectName("th_z_ee_lEdit")
        self.horizontalLayout_16.addWidget(self.th_z_ee_lEdit)
        self.th_z_rad_ee_lEdit = QtWidgets.QLineEdit(self.groupBox_5)
        self.th_z_rad_ee_lEdit.setObjectName("th_z_rad_ee_lEdit")
        self.horizontalLayout_16.addWidget(self.th_z_rad_ee_lEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.groupBox_6 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 500, 571, 161))
        self.groupBox_6.setObjectName("groupBox_6")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget2.setGeometry(QtCore.QRect(20, 60, 141, 27))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.get_joint_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.get_joint_btn.setObjectName("get_joint_btn")
        self.horizontalLayout_5.addWidget(self.get_joint_btn)
        self.clear_note_btn = QtWidgets.QPushButton(self.layoutWidget2)
        self.clear_note_btn.setObjectName("clear_note_btn")
        self.horizontalLayout_5.addWidget(self.clear_note_btn)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox_6)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 30, 141, 27))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_17 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_6.addWidget(self.label_17)
        self.get_note_lEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.get_note_lEdit.setObjectName("get_note_lEdit")
        self.horizontalLayout_6.addWidget(self.get_note_lEdit)
        self.show_note_joint_lEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.show_note_joint_lEdit.setGeometry(QtCore.QRect(20, 100, 541, 25))
        self.show_note_joint_lEdit.setObjectName("show_note_joint_lEdit")
        self.show_note_rad_joint_lEdit = QtWidgets.QLineEdit(self.groupBox_6)
        self.show_note_rad_joint_lEdit.setGeometry(QtCore.QRect(20, 130, 541, 25))
        self.show_note_rad_joint_lEdit.setObjectName("show_note_rad_joint_lEdit")
        self.widget2 = QtWidgets.QWidget(self.groupBox_6)
        self.widget2.setGeometry(QtCore.QRect(190, 30, 203, 60))
        self.widget2.setObjectName("widget2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.widget2)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.pos_list_comboBox = QtWidgets.QComboBox(self.widget2)
        self.pos_list_comboBox.setObjectName("pos_list_comboBox")
        self.horizontalLayout_10.addWidget(self.pos_list_comboBox)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 0, 0, 1, 1)
        self.del_pos_from_list_btn = QtWidgets.QPushButton(self.widget2)
        self.del_pos_from_list_btn.setObjectName("del_pos_from_list_btn")
        self.gridLayout_2.addWidget(self.del_pos_from_list_btn, 0, 1, 1, 1)
        self.add_pos_to_list_btn = QtWidgets.QPushButton(self.widget2)
        self.add_pos_to_list_btn.setObjectName("add_pos_to_list_btn")
        self.gridLayout_2.addWidget(self.add_pos_to_list_btn, 1, 0, 1, 1)
        self.show_list_btn = QtWidgets.QPushButton(self.widget2)
        self.show_list_btn.setObjectName("show_list_btn")
        self.gridLayout_2.addWidget(self.show_list_btn, 1, 1, 1, 1)
        self.widget3 = QtWidgets.QWidget(self.groupBox_6)
        self.widget3.setGeometry(QtCore.QRect(420, 30, 141, 60))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_23 = QtWidgets.QLabel(self.widget3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_15.addWidget(self.label_23)
        self.set_loop_times_lEdit = QtWidgets.QLineEdit(self.widget3)
        self.set_loop_times_lEdit.setObjectName("set_loop_times_lEdit")
        self.horizontalLayout_15.addWidget(self.set_loop_times_lEdit)
        self.horizontalLayout_15.setStretch(0, 2)
        self.horizontalLayout_15.setStretch(1, 4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_15)
        self.loop_move_btn = QtWidgets.QPushButton(self.widget3)
        self.loop_move_btn.setStyleSheet("color: rgb(239, 41, 41);")
        self.loop_move_btn.setObjectName("loop_move_btn")
        self.verticalLayout_6.addWidget(self.loop_move_btn)
        self.adjust_UR_EE_pos_gBox = QtWidgets.QGroupBox(self.centralwidget)
        self.adjust_UR_EE_pos_gBox.setGeometry(QtCore.QRect(10, 410, 321, 91))
        self.adjust_UR_EE_pos_gBox.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.adjust_UR_EE_pos_gBox.setObjectName("adjust_UR_EE_pos_gBox")
        self.layoutWidget_2 = QtWidgets.QWidget(self.adjust_UR_EE_pos_gBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(3, 19, 311, 71))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.ur_forward_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_forward_btn.setEnabled(False)
        self.ur_forward_btn.setObjectName("ur_forward_btn")
        self.gridLayout.addWidget(self.ur_forward_btn, 0, 0, 1, 1)
        self.ur_left_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_left_btn.setEnabled(False)
        self.ur_left_btn.setObjectName("ur_left_btn")
        self.gridLayout.addWidget(self.ur_left_btn, 0, 1, 1, 1)
        self.ur_up_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_up_btn.setEnabled(False)
        self.ur_up_btn.setObjectName("ur_up_btn")
        self.gridLayout.addWidget(self.ur_up_btn, 0, 2, 1, 1)
        self.ur_back_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_back_btn.setEnabled(False)
        self.ur_back_btn.setObjectName("ur_back_btn")
        self.gridLayout.addWidget(self.ur_back_btn, 1, 0, 1, 1)
        self.ur_right_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_right_btn.setEnabled(False)
        self.ur_right_btn.setObjectName("ur_right_btn")
        self.gridLayout.addWidget(self.ur_right_btn, 1, 1, 1, 1)
        self.ur_down_btn = QtWidgets.QPushButton(self.layoutWidget_2)
        self.ur_down_btn.setEnabled(False)
        self.ur_down_btn.setObjectName("ur_down_btn")
        self.gridLayout.addWidget(self.ur_down_btn, 1, 2, 1, 1)
        self.ur_stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ur_stop_btn.setEnabled(True)
        self.ur_stop_btn.setGeometry(QtCore.QRect(480, 450, 91, 61))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ur_stop_btn.setFont(font)
        self.ur_stop_btn.setStyleSheet("color: rgb(239, 41, 41);\n"
"font: 14pt \"Ubuntu\";")
        self.ur_stop_btn.setObjectName("ur_stop_btn")
        self.clear_ur_info_txt_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_ur_info_txt_btn.setGeometry(QtCore.QRect(350, 450, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_ur_info_txt_btn.setFont(font)
        self.clear_ur_info_txt_btn.setObjectName("clear_ur_info_txt_btn")
        self.groupBox_7 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_7.setGeometry(QtCore.QRect(600, 550, 221, 51))
        self.groupBox_7.setObjectName("groupBox_7")
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox_7)
        self.layoutWidget4.setGeometry(QtCore.QRect(50, 20, 116, 25))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.ur3_ch_btn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.ur3_ch_btn.setObjectName("ur3_ch_btn")
        self.horizontalLayout_7.addWidget(self.ur3_ch_btn)
        self.ur5_ch_btn = QtWidgets.QRadioButton(self.layoutWidget4)
        self.ur5_ch_btn.setObjectName("ur5_ch_btn")
        self.horizontalLayout_7.addWidget(self.ur5_ch_btn)
        self.groupBox_8 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_8.setGeometry(QtCore.QRect(600, 610, 221, 51))
        self.groupBox_8.setObjectName("groupBox_8")
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox_8)
        self.layoutWidget5.setGeometry(QtCore.QRect(30, 20, 171, 25))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.normal_install_btn = QtWidgets.QRadioButton(self.layoutWidget5)
        self.normal_install_btn.setObjectName("normal_install_btn")
        self.horizontalLayout_8.addWidget(self.normal_install_btn)
        self.down_install_btn = QtWidgets.QRadioButton(self.layoutWidget5)
        self.down_install_btn.setObjectName("down_install_btn")
        self.horizontalLayout_8.addWidget(self.down_install_btn)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 830, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Joints"))
        self.label_3.setText(_translate("MainWindow", "base"))
        self.label_4.setText(_translate("MainWindow", "shoulder"))
        self.label_5.setText(_translate("MainWindow", "elbow"))
        self.label_6.setText(_translate("MainWindow", "wrist1"))
        self.label_7.setText(_translate("MainWindow", "wrist2"))
        self.label_8.setText(_translate("MainWindow", "wrist3"))
        self.groupBox_2.setTitle(_translate("MainWindow", "UR INFO"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Input move"))
        self.label.setText(_translate("MainWindow", "Input joint angles( degree ):"))
        self.move_joint_angle_btn.setText(_translate("MainWindow", "Move"))
        self.clear_angle_btn.setText(_translate("MainWindow", "Clear"))
        self.label_2.setText(_translate("MainWindow", "Input joint angles( radian):"))
        self.move_joint_radian_btn.setText(_translate("MainWindow", "Move"))
        self.clear_radian_btn.setText(_translate("MainWindow", "Clear"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Get and move"))
        self.init2final_btn.setText(_translate("MainWindow", "INIT---> FINAL Move"))
        self.final2init_btn.setText(_translate("MainWindow", "FINAL--->INIT  Move"))
        self.label_10.setText(_translate("MainWindow", "Get FINAL pos (degree):"))
        self.get_final_ur_pos_btn.setText(_translate("MainWindow", "GET"))
        self.clear_final_ledit_btn.setText(_translate("MainWindow", "Clear"))
        self.label_9.setText(_translate("MainWindow", "Get INIT pos (degree):"))
        self.get_init_ur_pos_btn.setText(_translate("MainWindow", "GET"))
        self.clear_init_ledit_btn.setText(_translate("MainWindow", "Clear"))
        self.groupBox_5.setTitle(_translate("MainWindow", "EndEffector Pos and Atti"))
        self.label_11.setText(_translate("MainWindow", "X"))
        self.label_12.setText(_translate("MainWindow", "Y"))
        self.label_13.setText(_translate("MainWindow", "Z"))
        self.label_14.setText(_translate("MainWindow", "theta_x"))
        self.label_15.setText(_translate("MainWindow", "theta_y"))
        self.label_16.setText(_translate("MainWindow", "theta_z"))
        self.groupBox_6.setTitle(_translate("MainWindow", "GET and Loop Move "))
        self.get_joint_btn.setText(_translate("MainWindow", "Get"))
        self.clear_note_btn.setText(_translate("MainWindow", "Clear"))
        self.label_17.setText(_translate("MainWindow", "pos tag"))
        self.label_19.setText(_translate("MainWindow", "list"))
        self.del_pos_from_list_btn.setText(_translate("MainWindow", "Delete"))
        self.add_pos_to_list_btn.setText(_translate("MainWindow", "add to list"))
        self.show_list_btn.setText(_translate("MainWindow", "show list"))
        self.label_23.setText(_translate("MainWindow", "Times"))
        self.set_loop_times_lEdit.setPlaceholderText(_translate("MainWindow", "1"))
        self.loop_move_btn.setText(_translate("MainWindow", "list loop move"))
        self.adjust_UR_EE_pos_gBox.setTitle(_translate("MainWindow", "UR EE Pos step movement"))
        self.ur_forward_btn.setText(_translate("MainWindow", "⦿"))
        self.ur_left_btn.setText(_translate("MainWindow", "⇦"))
        self.ur_up_btn.setText(_translate("MainWindow", "⇧"))
        self.ur_back_btn.setText(_translate("MainWindow", "◯"))
        self.ur_right_btn.setText(_translate("MainWindow", "⇨"))
        self.ur_down_btn.setText(_translate("MainWindow", "⇩"))
        self.ur_stop_btn.setText(_translate("MainWindow", "STOP UR"))
        self.clear_ur_info_txt_btn.setText(_translate("MainWindow", "Clear UR INFO"))
        self.groupBox_7.setTitle(_translate("MainWindow", "UR Type"))
        self.ur3_ch_btn.setText(_translate("MainWindow", "UR3"))
        self.ur5_ch_btn.setText(_translate("MainWindow", "UR5"))
        self.groupBox_8.setTitle(_translate("MainWindow", "UR install type"))
        self.normal_install_btn.setText(_translate("MainWindow", "normal"))
        self.down_install_btn.setText(_translate("MainWindow", "down"))


